# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcKDA_old_cpp <- function(A) {
    .Call(`_GUILDS_calcKDA_old_cpp`, A)
}

calcKDA_new_cpp <- function(A) {
    .Call(`_GUILDS_calcKDA_new_cpp`, A)
}

calcKDA <- function(A) {
    .Call(`_GUILDS_calcKDA`, A)
}

